[project]
name = "crossandra"
version = "1.2.2"
description = "A simple tokenizer operating on enums with a decent amount of configuration"
authors = [{ email = "trag1c <trag1cdev@yahoo.com>" }]
license = { text = "MIT" }
urls = { repository = "https://github.com/trag1c/crossandra" }
readme = "README.md"
dependencies = ["result ~= 0.8.0"]

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"
